### ISSUE TITLE
Error while running command on cloud shell

### ISSUE THREAD

**Issue by visheshbalani** [benc-uk/smilr#24]
I get the following error when I run this command from module 2 of the AKS lab

az acr build --registry $ACR_NAME -g kube-lab --context . --file node/data-api/Dockerfile --image smilr/data-api

No module named 'pytz'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 251, in execute
    self.commands_loader.load_arguments(command)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 244, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 140, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 425, in default_arguments_loader
    op = handler or self.get_op_handler(operation)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 469, in get_op_handler
    op = import_module(mod_to_import)
  File "/opt/az/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/vishesh/.azure/cliextensions/acrbuildext/azext_acrbuildext/build.py", line 18, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

The python prompt gives version 3.5 and I have pip installed pytz 
Please let me know where I am going wrong and what to try

**Comment by benc-uk** [comment]
Closed as old
